---

# configure portage configuration and install required packages

- include: ../../../portage/tasks/gentoo/main.yml
  vars:
    portage_configuration:
      - section: "package.use"
        file: "virtual-jre"
        entries:
          - "virtual/jre headless-awt -alsa -cups"
          - ">=x11-libs/cairo-1.14.6 X"
          - ">=x11-libs/gdk-pixbuf-2.34.0 X"
    portage_packages:
      - { package: "virtual/jre" }
